//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.02 at 09:55:13 AM CST 
//

package com.jts.fortress;

import com.jts.fortress.arbac.AdminRole;
import com.jts.fortress.arbac.OrgUnit;
import com.jts.fortress.arbac.UserAdminRole;
import com.jts.fortress.rbac.Role;
import com.jts.fortress.rbac.Session;
import com.jts.fortress.rbac.User;
import com.jts.fortress.rbac.UserRole;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jts.fortress.model2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    //private final static QName _FortEntity_QNAME = new QName("", "fortEntity");
    private final static QName _FortUser_QNAME = new QName("", "fortUser");
    private final static QName _FortRole_QNAME = new QName("", "fortRole");
    private final static QName _FortOrgUnit_QNAME = new QName("", "fortOrgUnit");
    private final static QName _FortEntity_QNAME = new QName("", "fortEntity");
    private final static QName _FortAdminRole_QNAME = new QName("", "fortAdminRole");

    @XmlElementDecl(namespace = "", name = "fortEntity")
    public JAXBElement<FortEntity> createFortEntity(FortEntity value) {
        return new JAXBElement<FortEntity>(_FortEntity_QNAME, FortEntity.class, null, value);
    }


    @XmlElementDecl(namespace = "", name = "fortOrgUnit")
    public JAXBElement<com.jts.fortress.arbac.OrgUnit> createFortOrgUnit(OrgUnit value) {
        return new JAXBElement<OrgUnit>(_FortOrgUnit_QNAME, OrgUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.jts.fortress.rbac.Role }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "fortRole")
    public JAXBElement<com.jts.fortress.rbac.Role> createFortRole(com.jts.fortress.rbac.Role value) {
        return new JAXBElement<com.jts.fortress.rbac.Role>(_FortRole_QNAME, com.jts.fortress.rbac.Role.class, null, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.jts.fortress.rbac.Role }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "fortAdminRole")
    public JAXBElement<com.jts.fortress.arbac.AdminRole> createFortAdminRole(com.jts.fortress.arbac.AdminRole value) {
        return new JAXBElement<com.jts.fortress.arbac.AdminRole>(_FortAdminRole_QNAME, com.jts.fortress.arbac.AdminRole.class, null, value);
    }
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jts.fortress.model2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link User }
     *
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Session }
     * 
     */
    public Session createSession() {
        return new Session();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Role }
     *
     */
    public AdminRole createAdminRole() {
        return new AdminRole();
    }

    /**
     * Create an instance of {@link UserRole }
     * 
     */
    public UserRole createUserRole() {
        return new UserRole();
    }

    /**
     * Create an instance of {@link OrgUnit }
     * 
     */
    public OrgUnit createOrgUnit() {
        return new OrgUnit();
    }

    /**
     * Create an instance of {@link UserAdminRole }
     * 
     */
    public UserAdminRole createUserAdminRole() {
        return new UserAdminRole();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.jts.fortress.rbac.User }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "fortUser")
    public JAXBElement<com.jts.fortress.rbac.User> createFortUser(com.jts.fortress.rbac.User value) {
        return new JAXBElement<com.jts.fortress.rbac.User>(_FortUser_QNAME, com.jts.fortress.rbac.User.class, null, value);
    }
    /**
     * Create an instance of {@link User }
     * 
     */
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FortEntity }{@code >}}
     * 
     */
    //@XmlElementDecl(namespace = "", name = "fortEntity")
    //public JAXBElement<FortEntity> createFortEntity(FortEntity value) {
    //    return new JAXBElement<FortEntity>(_FortEntity_QNAME, FortEntity.class, null, value);
    //}

}
