//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.02 at 09:55:13 AM CST 
//

package com.jts.fortress;

import com.jts.fortress.pwpolicy.PswdPolicy;
import com.jts.fortress.rbac.PermGrant;
import com.jts.fortress.arbac.AdminRole;
import com.jts.fortress.arbac.OrgUnit;
import com.jts.fortress.arbac.UserAdminRole;
import com.jts.fortress.rbac.PermObj;
import com.jts.fortress.rbac.Permission;
import com.jts.fortress.rbac.Role;
import com.jts.fortress.rbac.RoleRelationship;
import com.jts.fortress.rbac.SDSet;
import com.jts.fortress.rbac.Session;
import com.jts.fortress.rbac.User;
import com.jts.fortress.rbac.UserRole;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.jts.fortress.model2 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory
{

    //private final static QName _FortEntity_QNAME = new QName("", "fortEntity");
    private final static QName _FortUser_QNAME = new QName("", "fortUser");
    private final static QName _FortSession_QNAME = new QName("", "fortSession");
    private final static QName _FortRole_QNAME = new QName("", "fortRole");
    private final static QName _FortGrant_QNAME = new QName("", "fortGrant");
    private final static QName _FortOrgUnit_QNAME = new QName("", "fortOrgUnit");
    private final static QName _FortEntity_QNAME = new QName("", "fortEntity");
    private final static QName _FortAdminRole_QNAME = new QName("", "fortAdminRole");
    private final static QName _FortUserRole_QNAME = new QName("", "fortUserRole");
    private final static QName _FortObject_QNAME = new QName("", "fortObject");
    private final static QName _FortPermission_QNAME = new QName("", "fortPermission");
    private final static QName _FortRoleRelationship_QNAME = new QName("", "fortRoleRelationship");
    private final static QName _FortSet_QNAME = new QName("", "fortSet");
    private final static QName _FortPolicy_QNAME = new QName("", "fortPolicy");



    @XmlElementDecl(namespace = "", name = "fortEntity")
    public JAXBElement<FortEntity> createFortEntity(FortEntity value)
    {
        return new JAXBElement<FortEntity>(_FortEntity_QNAME, FortEntity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.jts.fortress.rbac.SDSet }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fortSet")
    public JAXBElement<SDSet> createFortSet(SDSet value)
    {
        return new JAXBElement<SDSet>(_FortSet_QNAME, SDSet.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PswdPolicy }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fortPolicy")
    public JAXBElement<PswdPolicy> createFortPolicy(PswdPolicy value)
    {
        return new JAXBElement<PswdPolicy>(_FortPolicy_QNAME, PswdPolicy.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.jts.fortress.rbac.Session }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fortSession")
    public JAXBElement<Session> createFortSession(Session value)
    {
        return new JAXBElement<Session>(_FortSession_QNAME, Session.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.jts.fortress.rbac.User }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fortUser")
    public JAXBElement<User> createFortUser(User value)
    {
        return new JAXBElement<User>(_FortUser_QNAME, User.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.jts.fortress.rbac.UserRole }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fortUserRole")
    public JAXBElement<UserRole> createFortUserRole(UserRole value)
    {
        return new JAXBElement<UserRole>(_FortUserRole_QNAME, UserRole.class, null, value);
    }

    @XmlElementDecl(namespace = "", name = "fortOrgUnit")
    public JAXBElement<OrgUnit> createFortOrgUnit(OrgUnit value)
    {
        return new JAXBElement<OrgUnit>(_FortOrgUnit_QNAME, OrgUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.jts.fortress.rbac.Role }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fortRole")
    public JAXBElement<Role> createFortRole(Role value)
    {
        return new JAXBElement<Role>(_FortRole_QNAME, Role.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.jts.fortress.rbac.Role }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fortGrant")
    public JAXBElement<PermGrant> createFortGrant(PermGrant value)
    {
        return new JAXBElement<PermGrant>(_FortGrant_QNAME, PermGrant.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.jts.fortress.rbac.RoleRelationship}{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fortRoleRelationship")
    public JAXBElement<RoleRelationship> createFortRoleRelationship(RoleRelationship value)
    {
        return new JAXBElement<RoleRelationship>(_FortRoleRelationship_QNAME, RoleRelationship.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.jts.fortress.rbac.Role }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fortAdminRole")
    public JAXBElement<AdminRole> createFortAdminRole(AdminRole value)
    {
        return new JAXBElement<AdminRole>(_FortAdminRole_QNAME, AdminRole.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PermObj }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fortObject")
    public JAXBElement<PermObj> createFortObject(PermObj value)
    {
        return new JAXBElement<PermObj>(_FortObject_QNAME, PermObj.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link com.jts.fortress.rbac.Permission }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "fortPermission")
    public JAXBElement<Permission> createFortPermission(Permission value)
    {
        return new JAXBElement<Permission>(_FortObject_QNAME, Permission.class, null, value);
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jts.fortress.model2
     */
    public ObjectFactory()
    {
    }

    /**
     * Create an instance of {@link User }
     */
    public User createUser()
    {
        return new User();
    }

    /**
     * Create an instance of {@link PswdPolicy }
     */
    public PswdPolicy createPswdPolicy()
    {
        return new PswdPolicy();
    }

    /**
     * Create an instance of {@link Session }
     */
    public Session createSession()
    {
        return new Session();
    }

    /**
     * Create an instance of {@link SDSet }
     */
    public SDSet createSDset()
    {
        return new SDSet();
    }

    /**
     * Create an instance of {@link Role }
     */
    public Role createRole()
    {
        return new Role();
    }

    /**
     * Create an instance of {@link PermGrant }
     */
    public PermGrant createPermGrant()
    {
        return new PermGrant();
    }

    /**
     * Create an instance of {@link RoleRelationship }
     */
    public RoleRelationship createRoleRelationship()
    {
        return new RoleRelationship();
    }

    /**
     * Create an instance of {@link PermObj }
     */
    public PermObj createPermObj()
    {
        return new PermObj();
    }

    /**
     * Create an instance of {@link Permission }
     */
    public Permission createPermission()
    {
        return new Permission();
    }

    /**
     * Create an instance of {@link Role }
     */
    public AdminRole createAdminRole()
    {
        return new AdminRole();
    }

    /**
     * Create an instance of {@link UserRole }
     */
    public UserRole createUserRole()
    {
        return new UserRole();
    }

    /**
     * Create an instance of {@link OrgUnit }
     */
    public OrgUnit createOrgUnit()
    {
        return new OrgUnit();
    }

    /**
     * Create an instance of {@link UserAdminRole }
     */
    public UserAdminRole createUserAdminRole()
    {
        return new UserAdminRole();
    }
}
