hazelcast:
  cluster-name: dev-local
  jet:
    enabled: true
  network:
    join:
      multicast:
        enabled: false
      tcp-ip:
        enabled: false

  map:
    fortress.policies:
      in-memory-format: OBJECT
      backup-count: 0
      statistics-enabled: false
      time-to-live-seconds: 600
      max-idle-seconds: 600
      eviction:
        size: 1000
        max-size-policy: PER_NODE
        eviction-policy: LFU

    fortress.ous:
      in-memory-format: OBJECT
      backup-count: 0
      statistics-enabled: false
      time-to-live-seconds: 600
      max-idle-seconds: 600
      eviction:
        size: 1000
        max-size-policy: PER_NODE
        eviction-policy: LFU

    fortress.roles:
      in-memory-format: OBJECT
      backup-count: 0
      statistics-enabled: false
      time-to-live-seconds: 600
      max-idle-seconds: 600
      eviction:
        size: 1000
        max-size-policy: PER_NODE
        eviction-policy: LFU

    fortress.admin.roles:
      in-memory-format: OBJECT
      backup-count: 0
      statistics-enabled: false
      time-to-live-seconds: 600
      max-idle-seconds: 600
      eviction:
        size: 1000
        max-size-policy: PER_NODE
        eviction-policy: LFU

    fortress.pso:
      in-memory-format: OBJECT
      backup-count: 0
      statistics-enabled: false
      time-to-live-seconds: 600
      max-idle-seconds: 600
      eviction:
        size: 100000
        max-size-policy: PER_NODE
        eviction-policy: LFU

    fortress.uso:
      in-memory-format: OBJECT
      backup-count: 0
      statistics-enabled: false
      time-to-live-seconds: 600
      max-idle-seconds: 600
      eviction:
        size: 100000
        max-size-policy: PER_NODE
        eviction-policy: LFU

    fortress.dsd:
      in-memory-format: OBJECT
      backup-count: 0
      statistics-enabled: false
      time-to-live-seconds: 3600
      max-idle-seconds: 3600
      eviction:
        size: 1000
        max-size-policy: PER_NODE
        eviction-policy: LFU

    fortress.ssd:
      in-memory-format: OBJECT
      backup-count: 0
      statistics-enabled: false
      time-to-live-seconds: 600
      max-idle-seconds: 600
      eviction:
        size: 1000
        max-size-policy: PER_NODE
        eviction-policy: LFU